<a href="https://colab.research.google.com/github/Rawatkhushi/ML-Practice-Projects/blob/main/0.%20Learnings/Pandas_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Pandas**

###**What**
* python library works with structured data - table, csv files, spreadsheet

###**How**
* used in cleaning/analyzing the dataset before training ML model on it.

###**Why**
* because the data can be inconsistent. For ex,
1. missing values
2. duplicate rows
3. improper format
4. textual values mixed with strings

###**Alternatives**
* Polars : faster than pandas, lower memory usage, built on **Rust**
* PySpark : industry standard, less beginner friendly, distributed clusters

###**Data Structure in Pandas**

####**Series** : 1d array of any data type

####**DataFram** : a 2d (rows and columns) structure

In [2]:
import pandas as pd

###**Series from a List**

In [3]:
#numbers
marks = [1, 2]

new = pd.Series(marks)

#strings
name = ['khushi', 'rawat']
newser = pd.Series(name)

In [4]:
#custom index

pd.Series(marks, index = name)

khushi    1
rawat     2
dtype: int64

In [5]:
#setting a name

pd.Series(marks, name = 'Khushi Rawat')

0    1
1    2
Name: Khushi Rawat, dtype: int64

###**Series from a dict**

In [6]:
info = {
    'name' : 'khushi',
    'age' : 22,
    'address' : 'Uttar Pradesh'
}

information = pd.Series(info)
information

name              khushi
age                   22
address    Uttar Pradesh
dtype: object

###**Series Attribute**

In [7]:
#size
information.size

3

In [8]:
#name
information.name

In [9]:
#dtype

information.dtype #dtype("O") means Object/String

dtype('O')

In [10]:
# is unique
information.is_unique   #true

pd.Series([1,1,2,3,4]).is_unique

False

In [11]:
#index
information.index

Index(['name', 'age', 'address'], dtype='object')

In [12]:
temp = [1,2,3,4,5,6,7]
tempsr = pd.Series(temp)
tempsr.index

RangeIndex(start=0, stop=7, step=1)

In [13]:
#values

tempsr.values

array([1, 2, 3, 4, 5, 6, 7])

##**Series using existing datasets**

In [42]:
#deprecated
#pd.read_csv('/content/placement.csv', squeeze = True)

In [43]:
#with 2 cols

df = pd.read_csv('/content/placement.csv', index_col = 0) #index_col can be given any col name or index of the col
temp3 = df.squeeze() #only used for series conversion when dataframe has only one attribute
temp3 #csv has multiple cols therefore no change

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

##**Series methods**

In [45]:
df = pd.read_csv('/content/placement.csv')
subs = df.iloc[:, 1]
subs.head() #default 5 rows

0    6.8
1    5.9
2    5.3
3    7.4
4    5.8
Name: cgpa, dtype: float64

In [46]:
subs.head(10)

0    6.8
1    5.9
2    5.3
3    7.4
4    5.8
5    7.1
6    5.7
7    5.0
8    6.1
9    5.1
Name: cgpa, dtype: float64

In [47]:
subs.tail() #default bottom 5rows

95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, dtype: float64

In [48]:
subs.tail(2)

98    6.3
99    6.2
Name: cgpa, dtype: float64

In [49]:
subs.sample() #random 1 row

50    3.5
Name: cgpa, dtype: float64

In [50]:
subs.sample(4)

17    3.3
79    6.5
77    7.3
13    6.4
Name: cgpa, dtype: float64

In [51]:
#value counts

subs.value_counts() #counts of cgpa

cgpa
4.9    6
6.1    5
5.2    5
6.0    5
7.0    5
5.7    4
6.8    4
7.3    4
5.4    4
6.5    4
4.8    4
7.5    3
4.7    3
5.1    3
6.3    3
5.0    3
6.9    3
4.0    2
7.1    2
5.3    2
4.4    2
5.8    2
6.4    2
6.7    2
8.1    2
6.6    2
7.6    2
7.4    1
5.9    1
3.9    1
3.3    1
7.8    1
8.3    1
3.5    1
4.6    1
8.5    1
8.0    1
4.3    1
6.2    1
Name: count, dtype: int64

In [54]:
#sort values (not changing the original)
subs.sort_values() #default asc to desc

17    3.3
50    3.5
31    3.9
18    4.0
68    4.0
     ...
58    8.0
65    8.1
37    8.1
53    8.3
69    8.5
Name: cgpa, Length: 100, dtype: float64

In [57]:
subs.sort_values().head(1) #lowest cgpa

17    3.3
Name: cgpa, dtype: float64

In [63]:
#subs.sort_values(inplace=True)
#This Series is a view of some other array, to sort in-place you must create a copy

subs = df.iloc[:, 1].copy()
subs.sort_values(inplace=True)
subs

17    3.3
50    3.5
31    3.9
18    4.0
68    4.0
     ...
58    8.0
65    8.1
37    8.1
53    8.3
69    8.5
Name: cgpa, Length: 100, dtype: float64