<a href="https://colab.research.google.com/github/Rawatkhushi/ML-Practice-Projects/blob/main/0.%20Learnings/Pandas_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Pandas**

###**What**
* python library works with structured data - table, csv files, spreadsheet

###**How**
* used in cleaning/analyzing the dataset before training ML model on it.

###**Why**
* because the data can be inconsistent. For ex,
1. missing values
2. duplicate rows
3. improper format
4. textual values mixed with strings

###**Alternatives**
* Polars : faster than pandas, lower memory usage, built on **Rust**
* PySpark : industry standard, less beginner friendly, distributed clusters

###**Data Structure in Pandas**

####**Series** : 1d array of any data type

####**DataFram** : a 2d (rows and columns) structure

In [15]:
import pandas as pd

###**Series from a List**

In [16]:
#numbers
marks = [1, 2]

new = pd.Series(marks)

#strings
name = ['khushi', 'rawat']
newser = pd.Series(name)

In [17]:
#custom index

pd.Series(marks, index = name)

khushi    1
rawat     2
dtype: int64

In [18]:
#setting a name

pd.Series(marks, name = 'Khushi Rawat')

0    1
1    2
Name: Khushi Rawat, dtype: int64

###**Series from a dict**

In [19]:
info = {
    'name' : 'khushi',
    'age' : 22,
    'address' : 'Uttar Pradesh'
}

information = pd.Series(info)
information

name              khushi
age                   22
address    Uttar Pradesh
dtype: object

###**Series Attribute**

In [20]:
#size
information.size

3

In [21]:
#name
information.name

In [22]:
#dtype

information.dtype #dtype("O") means Object/String

dtype('O')

In [23]:
# is unique
information.is_unique   #true

pd.Series([1,1,2,3,4]).is_unique

False

In [24]:
#index
information.index

Index(['name', 'age', 'address'], dtype='object')

In [25]:
temp = [1,2,3,4,5,6,7]
tempsr = pd.Series(temp)
tempsr.index

RangeIndex(start=0, stop=7, step=1)

In [26]:
#values

tempsr.values

array([1, 2, 3, 4, 5, 6, 7])

##**Series using existing datasets**

In [27]:
#deprecated
#pd.read_csv('/content/placement.csv', squeeze = True)

In [28]:
#with 2 cols

df = pd.read_csv('/content/placement.csv', index_col = 0) #index_col can be given any col name or index of the col
temp3 = df.squeeze() #only used for series conversion when dataframe has only one attribute
temp3 #csv has multiple cols therefore no change

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

##**Series methods**

In [29]:
df = pd.read_csv('/content/placement.csv')
subs = df.iloc[:, 1]
subs.head() #default 5 rows

0    6.8
1    5.9
2    5.3
3    7.4
4    5.8
Name: cgpa, dtype: float64

In [30]:
subs.head(10)

0    6.8
1    5.9
2    5.3
3    7.4
4    5.8
5    7.1
6    5.7
7    5.0
8    6.1
9    5.1
Name: cgpa, dtype: float64

In [31]:
subs.tail() #default bottom 5rows

95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, dtype: float64

In [32]:
subs.tail(2)

98    6.3
99    6.2
Name: cgpa, dtype: float64

In [33]:
subs.sample() #random 1 row

43    6.8
Name: cgpa, dtype: float64

In [34]:
subs.sample(4)

11    6.9
75    4.8
56    6.1
90    7.3
Name: cgpa, dtype: float64

In [35]:
#value counts

subs.value_counts() #counts of cgpa

cgpa
4.9    6
6.1    5
5.2    5
6.0    5
7.0    5
5.7    4
6.8    4
7.3    4
5.4    4
6.5    4
4.8    4
7.5    3
4.7    3
5.1    3
6.3    3
5.0    3
6.9    3
4.0    2
7.1    2
5.3    2
4.4    2
5.8    2
6.4    2
6.7    2
8.1    2
6.6    2
7.6    2
7.4    1
5.9    1
3.9    1
3.3    1
7.8    1
8.3    1
3.5    1
4.6    1
8.5    1
8.0    1
4.3    1
6.2    1
Name: count, dtype: int64

In [36]:
#sort values (not changing the original)
subs.sort_values() #default asc to desc

17    3.3
50    3.5
31    3.9
18    4.0
68    4.0
     ...
58    8.0
65    8.1
37    8.1
53    8.3
69    8.5
Name: cgpa, Length: 100, dtype: float64

In [37]:
subs.sort_values().head(1) #lowest cgpa

17    3.3
Name: cgpa, dtype: float64

In [38]:
#subs.sort_values(inplace=True)
#This Series is a view of some other array, to sort in-place you must create a copy

subs = df.iloc[:, 1].copy()
subs.sort_values(inplace=True)
subs

17    3.3
50    3.5
31    3.9
18    4.0
68    4.0
     ...
58    8.0
65    8.1
37    8.1
53    8.3
69    8.5
Name: cgpa, Length: 100, dtype: float64

In [39]:
#sort_index()
subs.sort_index()

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

##**Series Maths methods**

In [40]:
#count() - doesn't count null values whereas size() does
subs.count()

np.int64(100)

In [41]:
#sum , product
subs.sum()
subs.product()

np.float64(8.510398451077018e+76)

In [42]:
#mean
subs.mean()

np.float64(5.990999999999999)

In [43]:
#median
subs.median()

6.0

In [44]:
#mode
subs.mode()

0    4.9
Name: cgpa, dtype: float64

In [45]:
#standard Deviation
subs.std()

1.1436336737775692

In [46]:
#variance
subs.var()

1.3078979797979797

In [47]:
#min and max
subs.min()

3.3

In [48]:
#describe
subs.describe()

count    100.000000
mean       5.991000
std        1.143634
min        3.300000
25%        5.075000
50%        6.000000
75%        6.900000
max        8.500000
Name: cgpa, dtype: float64

##**Series indexing**

In [49]:
#integer indexing
x = pd.Series([1,2,3,4,5,6,7,8,9])
x[4]

np.int64(5)

In [50]:
#negative indexing
#x[-4] doesnt work
x[-3:] #works

#if the custom index is String, negative indexing wll work

6    7
7    8
8    9
dtype: int64

In [51]:
#slicing
df = pd.read_csv('/content/placement.csv')
subs = df.iloc[:, 2]
subs[2:4]

2    121.0
3    132.0
Name: iq, dtype: float64

In [52]:
#negative slicing
subs[-3:]

97    182.0
98    103.0
99    113.0
Name: iq, dtype: float64

In [53]:
#fancy indexing
subs[[1,3,5]]

1    106.0
3    132.0
5     48.0
Name: iq, dtype: float64

##**Editing Series**

In [54]:
#using indexing
subs[1] = 200
subs

/tmp/ipykernel_3216/1989763703.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subs[1] = 200

0     123.0
1     200.0
2     121.0
3     132.0
4     142.0
      ...
95    200.0
96     42.0
97    182.0
98    103.0
99    113.0
Name: iq, Length: 100, dtype: float64

In [55]:
#what if index doesnt exist
subs[200] = 90 #new index with value is added
subs

/tmp/ipykernel_3216/1045376136.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subs[200] = 90 #new index with value is added

0      123.0
1      200.0
2      121.0
3      132.0
4      142.0
       ...
96      42.0
97     182.0
98     103.0
99     113.0
200     90.0
Name: iq, Length: 101, dtype: float64

In [56]:
#slicing
subs[2:4] = [100, 100]
subs

0      123.0
1      200.0
2      100.0
3      100.0
4      142.0
       ...
96      42.0
97     182.0
98     103.0
99     113.0
200     90.0
Name: iq, Length: 101, dtype: float64

In [57]:
#fancy indexing

subs[[0, 1, 2]] = [0,0,0]
subs

0        0.0
1        0.0
2        0.0
3      100.0
4      142.0
       ...
96      42.0
97     182.0
98     103.0
99     113.0
200     90.0
Name: iq, Length: 101, dtype: float64

##**Series with Python Functionality**

In [58]:
#length/min/max/type/dir
print(len(subs))
print(type(subs))
print(dir(subs))
print(sorted(subs))
print(min(subs))
print(max(subs))

101
<class 'pandas.core.series.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__bool__', '__class__', '__column_consortium_standard__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append', '_arith_method', '_as_manager', '_attrs', '_binop', '_cacher', '_can_hold_na', '_check_inplace_and_allows_duplicate_labels', '_check_is_chained_assignment_possible', '_check_label_or_level_ambiguity', '_check_setitem_copy', '_clear_item_cache', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_data', '_deprecate_downcast', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cacher', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_cached', '_is_copy', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_is_view', '_is_view_after_cow_rules', '_item_cache', '_ixs', '_logical_func', '_logical_method', '_map_values', '_maybe_update_cacher', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_protect_consolidate', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_replace_single', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_reset_cacher', '_set_as_cached', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_is_copy', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_take_with_is_copy', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'backfill', 'between', 'between_time', 'bfill', 'bool', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first', 'first_valid_index', 'flags', 'floordiv', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pad', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'ravel', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swapaxes', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'view', 'where', 'xs']
[0.0, 0.0, 0.0, 37.0, 42.0, 45.0, 48.0, 50.0, 52.0, 61.0, 61.0, 63.0, 64.0, 65.0, 66.0, 66.0, 75.0, 79.0, 81.0, 86.0, 87.0, 89.0, 90.0, 90.0, 90.0, 90.0, 91.0, 96.0, 100.0, 100.0, 102.0, 103.0, 103.0, 107.0, 109.0, 110.0, 112.0, 112.0, 112.0, 113.0, 114.0, 114.0, 114.0, 116.0, 116.0, 118.0, 120.0, 120.0, 120.0, 121.0, 124.0, 127.0, 128.0, 128.0, 128.0, 130.0, 130.0, 132.0, 132.0, 132.0, 134.0, 135.0, 137.0, 138.0, 138.0, 139.0, 139.0, 139.0, 140.0, 141.0, 141.0, 141.0, 142.0, 143.0, 146.0, 149.0, 149.0, 149.0, 151.0, 151.0, 154.0, 155.0, 156.0, 158.0, 160.0, 161.0, 163.0, 166.0, 166.0, 168.0, 169.0, 169.0, 175.0, 176.0, 182.0, 183.0, 196.0, 199.0, 200.0, 224.0, 233.0]
0.0
233.0

In [59]:
#type conversion
list(subs)
dict(subs)

{0: np.float64(0.0),
 1: np.float64(0.0),
 2: np.float64(0.0),
 3: np.float64(100.0),
 4: np.float64(142.0),
 5: np.float64(48.0),
 6: np.float64(143.0),
 7: np.float64(63.0),
 8: np.float64(156.0),
 9: np.float64(66.0),
 10: np.float64(45.0),
 11: np.float64(138.0),
 12: np.float64(139.0),
 13: np.float64(116.0),
 14: np.float64(103.0),
 15: np.float64(176.0),
 16: np.float64(224.0),
 17: np.float64(183.0),
 18: np.float64(100.0),
 19: np.float64(132.0),
 20: np.float64(120.0),
 21: np.float64(151.0),
 22: np.float64(120.0),
 23: np.float64(87.0),
 24: np.float64(121.0),
 25: np.float64(91.0),
 26: np.float64(199.0),
 27: np.float64(124.0),
 28: np.float64(90.0),
 29: np.float64(112.0),
 30: np.float64(128.0),
 31: np.float64(109.0),
 32: np.float64(139.0),
 33: np.float64(149.0),
 34: np.float64(163.0),
 35: np.float64(90.0),
 36: np.float64(140.0),
 37: np.float64(149.0),
 38: np.float64(160.0),
 39: np.float64(146.0),
 40: np.float64(134.0),
 41: np.float64(114.0),
 42: np.float64(89.0),
 43: np.float64(141.0),
 44: np.float64(61.0),
 45: np.float64(66.0),
 46: np.float64(114.0),
 47: np.float64(161.0),
 48: np.float64(138.0),
 49: np.float64(135.0),
 50: np.float64(233.0),
 51: np.float64(141.0),
 52: np.float64(175.0),
 53: np.float64(168.0),
 54: np.float64(141.0),
 55: np.float64(114.0),
 56: np.float64(65.0),
 57: np.float64(130.0),
 58: np.float64(79.0),
 59: np.float64(112.0),
 60: np.float64(139.0),
 61: np.float64(137.0),
 62: np.float64(102.0),
 63: np.float64(128.0),
 64: np.float64(64.0),
 65: np.float64(166.0),
 66: np.float64(96.0),
 67: np.float64(118.0),
 68: np.float64(75.0),
 69: np.float64(120.0),
 70: np.float64(127.0),
 71: np.float64(132.0),
 72: np.float64(116.0),
 73: np.float64(61.0),
 74: np.float64(154.0),
 75: np.float64(169.0),
 76: np.float64(155.0),
 77: np.float64(50.0),
 78: np.float64(81.0),
 79: np.float64(90.0),
 80: np.float64(196.0),
 81: np.float64(107.0),
 82: np.float64(37.0),
 83: np.float64(130.0),
 84: np.float64(169.0),
 85: np.float64(166.0),
 86: np.float64(128.0),
 87: np.float64(132.0),
 88: np.float64(149.0),
 89: np.float64(151.0),
 90: np.float64(86.0),
 91: np.float64(158.0),
 92: np.float64(110.0),
 93: np.float64(112.0),
 94: np.float64(52.0),
 95: np.float64(200.0),
 96: np.float64(42.0),
 97: np.float64(182.0),
 98: np.float64(103.0),
 99: np.float64(113.0),
 200: np.float64(90.0)}

In [60]:
#membership operator - only works on index

99 in subs
#or
#'khushi' in subs, if indexes were string

True

In [61]:
#looping - iterates on values

for i in subs:
  print(i)

0.0
0.0
0.0
100.0
142.0
48.0
143.0
63.0
156.0
66.0
45.0
138.0
139.0
116.0
103.0
176.0
224.0
183.0
100.0
132.0
120.0
151.0
120.0
87.0
121.0
91.0
199.0
124.0
90.0
112.0
128.0
109.0
139.0
149.0
163.0
90.0
140.0
149.0
160.0
146.0
134.0
114.0
89.0
141.0
61.0
66.0
114.0
161.0
138.0
135.0
233.0
141.0
175.0
168.0
141.0
114.0
65.0
130.0
79.0
112.0
139.0
137.0
102.0
128.0
64.0
166.0
96.0
118.0
75.0
120.0
127.0
132.0
116.0
61.0
154.0
169.0
155.0
50.0
81.0
90.0
196.0
107.0
37.0
130.0
169.0
166.0
128.0
132.0
149.0
151.0
86.0
158.0
110.0
112.0
52.0
200.0
42.0
182.0
103.0
113.0
90.0

In [62]:
#arithmetic operators
100 - subs

0      100.0
1      100.0
2      100.0
3        0.0
4      -42.0
       ...
96      58.0
97     -82.0
98      -3.0
99     -13.0
200     10.0
Name: iq, Length: 101, dtype: float64