<a href="https://colab.research.google.com/github/Rawatkhushi/ML-Practice-Projects/blob/main/0.%20Learnings/Pandas_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Pandas**

###**What**
* python library works with structured data - table, csv files, spreadsheet

###**How**
* used in cleaning/analyzing the dataset before training ML model on it.

###**Why**
* because the data can be inconsistent. For ex,
1. missing values
2. duplicate rows
3. improper format
4. textual values mixed with strings

###**Alternatives**
* Polars : faster than pandas, lower memory usage, built on **Rust**
* PySpark : industry standard, less beginner friendly, distributed clusters

###**Data Structure in Pandas**

####**Series** : 1d array of any data type

####**DataFram** : a 2d (rows and columns) structure

In [15]:
import pandas as pd

###**Series from a List**

In [16]:
#numbers
marks = [1, 2]

new = pd.Series(marks)

#strings
name = ['khushi', 'rawat']
newser = pd.Series(name)

In [17]:
#custom index

pd.Series(marks, index = name)

khushi    1
rawat     2
dtype: int64

In [18]:
#setting a name

pd.Series(marks, name = 'Khushi Rawat')

0    1
1    2
Name: Khushi Rawat, dtype: int64

###**Series from a dict**

In [19]:
info = {
    'name' : 'khushi',
    'age' : 22,
    'address' : 'Uttar Pradesh'
}

information = pd.Series(info)
information

name              khushi
age                   22
address    Uttar Pradesh
dtype: object

###**Series Attribute**

In [20]:
#size
information.size

3

In [21]:
#name
information.name

In [22]:
#dtype

information.dtype #dtype("O") means Object/String

dtype('O')

In [23]:
# is unique
information.is_unique   #true

pd.Series([1,1,2,3,4]).is_unique

False

In [24]:
#index
information.index

Index(['name', 'age', 'address'], dtype='object')

In [25]:
temp = [1,2,3,4,5,6,7]
tempsr = pd.Series(temp)
tempsr.index

RangeIndex(start=0, stop=7, step=1)

In [26]:
#values

tempsr.values

array([1, 2, 3, 4, 5, 6, 7])

##**Series using existing datasets**

In [27]:
#deprecated
#pd.read_csv('/content/placement.csv', squeeze = True)

In [28]:
#with 2 cols

df = pd.read_csv('/content/placement.csv', index_col = 0) #index_col can be given any col name or index of the col
temp3 = df.squeeze() #only used for series conversion when dataframe has only one attribute
temp3 #csv has multiple cols therefore no change

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

##**Series methods**

In [29]:
df = pd.read_csv('/content/placement.csv')
subs = df.iloc[:, 1]
subs.head() #default 5 rows

0    6.8
1    5.9
2    5.3
3    7.4
4    5.8
Name: cgpa, dtype: float64

In [30]:
subs.head(10)

0    6.8
1    5.9
2    5.3
3    7.4
4    5.8
5    7.1
6    5.7
7    5.0
8    6.1
9    5.1
Name: cgpa, dtype: float64

In [31]:
subs.tail() #default bottom 5rows

95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, dtype: float64

In [32]:
subs.tail(2)

98    6.3
99    6.2
Name: cgpa, dtype: float64

In [33]:
subs.sample() #random 1 row

99    6.2
Name: cgpa, dtype: float64

In [34]:
subs.sample(4)

87    5.7
91    7.5
29    7.0
30    7.6
Name: cgpa, dtype: float64

In [35]:
#value counts

subs.value_counts() #counts of cgpa

cgpa
4.9    6
6.1    5
5.2    5
6.0    5
7.0    5
5.7    4
6.8    4
7.3    4
5.4    4
6.5    4
4.8    4
7.5    3
4.7    3
5.1    3
6.3    3
5.0    3
6.9    3
4.0    2
7.1    2
5.3    2
4.4    2
5.8    2
6.4    2
6.7    2
8.1    2
6.6    2
7.6    2
7.4    1
5.9    1
3.9    1
3.3    1
7.8    1
8.3    1
3.5    1
4.6    1
8.5    1
8.0    1
4.3    1
6.2    1
Name: count, dtype: int64

In [36]:
#sort values (not changing the original)
subs.sort_values() #default asc to desc

17    3.3
50    3.5
31    3.9
18    4.0
68    4.0
     ...
58    8.0
65    8.1
37    8.1
53    8.3
69    8.5
Name: cgpa, Length: 100, dtype: float64

In [37]:
subs.sort_values().head(1) #lowest cgpa

17    3.3
Name: cgpa, dtype: float64

In [38]:
#subs.sort_values(inplace=True)
#This Series is a view of some other array, to sort in-place you must create a copy

subs = df.iloc[:, 1].copy()
subs.sort_values(inplace=True)
subs

17    3.3
50    3.5
31    3.9
18    4.0
68    4.0
     ...
58    8.0
65    8.1
37    8.1
53    8.3
69    8.5
Name: cgpa, Length: 100, dtype: float64

In [39]:
#sort_index()
subs.sort_index()

0     6.8
1     5.9
2     5.3
3     7.4
4     5.8
     ...
95    4.3
96    4.4
97    6.7
98    6.3
99    6.2
Name: cgpa, Length: 100, dtype: float64

##**Series Maths methods**

In [40]:
#count() - doesn't count null values whereas size() does
subs.count()

np.int64(100)

In [41]:
#sum , product
subs.sum()
subs.product()

np.float64(8.510398451077018e+76)

In [42]:
#mean
subs.mean()

np.float64(5.990999999999999)

In [43]:
#median
subs.median()

6.0

In [44]:
#mode
subs.mode()

0    4.9
Name: cgpa, dtype: float64

In [45]:
#standard Deviation
subs.std()

1.1436336737775692

In [46]:
#variance
subs.var()

1.3078979797979797

In [47]:
#min and max
subs.min()

3.3

In [48]:
#describe
subs.describe()

count    100.000000
mean       5.991000
std        1.143634
min        3.300000
25%        5.075000
50%        6.000000
75%        6.900000
max        8.500000
Name: cgpa, dtype: float64

##**Series indexing**

In [49]:
#integer indexing
x = pd.Series([1,2,3,4,5,6,7,8,9])
x[4]

np.int64(5)

In [65]:
#negative indexing
#x[-4] doesnt work
x[-3:] #works

#if the custom index is String, negative indexing wll work

6    7
7    8
8    9
dtype: int64

In [57]:
#slicing
df = pd.read_csv('/content/placement.csv')
subs = df.iloc[:, 2]
subs[2:4]

2    121.0
3    132.0
Name: iq, dtype: float64

In [59]:
#negative slicing
subs[-3:]

97    182.0
98    103.0
99    113.0
Name: iq, dtype: float64

In [66]:
#fancy indexing
subs[[1,3,5]]

1    106.0
3    132.0
5     48.0
Name: iq, dtype: float64